import type { JsonObject } from "./json.js";

export type GameCommandErrorCode =
  | "GAME_NOT_ACTIVE"
  | "INVALID_PHASE"
  | "NOT_CURRENT_PLAYER"
  | "PHASE_SEQUENCE_MISMATCH"
  | "CLIENT_STATE_VERSION_AHEAD"
  | "PHASE_DEADLINE_EXPIRED"
  | "CONTEXT_VERSION_MISMATCH"
  | "CARD_NOT_FOUND"
  | "CARD_NOT_IN_HAND"
  | "INVALID_CARD_TYPE"
  | "ATTACK_GROUP_NOT_FOUND"
  | "ATTACK_GROUP_LIMIT_REACHED"
  | "ATTRIBUTE_MISMATCH"
  | "CHAIN_NOT_ALLOWED"
  | "INSUFFICIENT_MANA"
  | "INVALID_TARGET"
  | "INVALID_EFFECT_INPUT"
  | "SUPPORT_ALREADY_FINISHED"
  | "HAND_LIMIT_REACHED"
  | "EFFECT_VALIDATION_FAILED"
  | "EFFECT_PLANNING_FAILED"
  | "COMMAND_ALREADY_PROCESSED"
  | "INTERNAL_INVARIANT_VIOLATION";

export type GameCommandError = {
  code: GameCommandErrorCode;
  message: string;
  details?: JsonObject;
};
