import type { CardCatalogInput } from "@disastar/game-engine/contracts";

export const INITIAL_CARD_CATALOG_INPUT: CardCatalogInput = {
  version: "initial-catalog-v1",
  definitions: [
    {
      id: "mana-a",
      name: "みなもとA",
      attribute: "attributeA",
      cardType: "mana",
      manaAmount: 1,
    },
    {
      id: "mana-b",
      name: "みなもとB",
      attribute: "attributeB",
      cardType: "mana",
      manaAmount: 1,
    },
    {
      id: "mana-c",
      name: "みなもとC",
      attribute: "attributeC",
      cardType: "mana",
      manaAmount: 1,
    },
    {
      id: "attack-1",
      name: "炎の斥候",
      attribute: "attributeA",
      cardType: "attack",
      cost: 1,
      basePower: 2,
      chainableCardIds: ["attack-2", "attack-3"],
      effects: [],
    },
    {
      id: "attack-2",
      name: "炎の衛士",
      attribute: "attributeA",
      cardType: "attack",
      cost: 2,
      basePower: 3,
      chainableCardIds: ["attack-3"],
      effects: [],
    },
    {
      id: "attack-3",
      name: "炎の騎士",
      attribute: "attributeA",
      cardType: "attack",
      cost: 3,
      basePower: 5,
      chainableCardIds: [],
      effects: [],
    },
    {
      id: "attack-4",
      name: "水の斥候",
      attribute: "attributeB",
      cardType: "attack",
      cost: 1,
      basePower: 2,
      chainableCardIds: ["attack-5", "attack-6"],
      effects: [],
    },
    {
      id: "attack-5",
      name: "水の衛士",
      attribute: "attributeB",
      cardType: "attack",
      cost: 2,
      basePower: 3,
      chainableCardIds: ["attack-6"],
      effects: [],
    },
    {
      id: "attack-6",
      name: "水の騎士",
      attribute: "attributeB",
      cardType: "attack",
      cost: 3,
      basePower: 5,
      chainableCardIds: [],
      effects: [],
    },
    {
      id: "attack-7",
      name: "風の斥候",
      attribute: "attributeC",
      cardType: "attack",
      cost: 1,
      basePower: 2,
      chainableCardIds: ["attack-8"],
      effects: [],
    },
    {
      id: "attack-8",
      name: "風の騎士",
      attribute: "attributeC",
      cardType: "attack",
      cost: 2,
      basePower: 4,
      chainableCardIds: [],
      effects: [],
    },
    {
      id: "attack-9",
      name: "炎の守り手",
      attribute: "attributeA",
      cardType: "attack",
      cost: 2,
      basePower: 4,
      chainableCardIds: [],
      effects: [],
    },
    {
      id: "attack-10",
      name: "水の守り手",
      attribute: "attributeB",
      cardType: "attack",
      cost: 2,
      basePower: 4,
      chainableCardIds: [],
      effects: [],
    },
    {
      id: "attack-11",
      name: "風の守り手",
      attribute: "attributeC",
      cardType: "attack",
      cost: 2,
      basePower: 4,
      chainableCardIds: [],
      effects: [],
    },
    {
      id: "support-fire-001",
      name: "炎の強化",
      attribute: "attributeA",
      cardType: "support",
      cost: 2,
      duration: "untilRoundEnd",
      effects: [
        {
          effectId: "increase-group-power",
          type: "modifyPower",
          activationType: "continuous",
          scope: "groupPower",
          operation: "add",
          value: 3,
          targetRule: {
            required: true,
            minTargets: 1,
            maxTargets: 1,
            side: "self",
            zones: ["attackGroup"],
            allowSourceCard: false,
          },
        },
      ],
    },
    {
      id: "support-water-001",
      name: "水鏡",
      attribute: "attributeB",
      cardType: "support",
      cost: 2,
      duration: "instant",
      effects: [
        {
          effectId: "remove-opponent-support",
          type: "removeSupportCard",
          activationType: "onPlay",
          targetRule: {
            required: true,
            minTargets: 1,
            maxTargets: 1,
            side: "opponent",
            zones: ["supportCard"],
            allowSourceCard: false,
          },
        },
      ],
    },
    {
      id: "support-water-002",
      name: "源流封鎖",
      attribute: "attributeB",
      cardType: "support",
      cost: 3,
      duration: "instant",
      effects: [
        {
          effectId: "reduce-opponent-mana",
          type: "reduceMana",
          activationType: "onPlay",
          amount: 2,
          targetRule: {
            required: true,
            minTargets: 1,
            maxTargets: 1,
            side: "opponent",
            zones: ["mana"],
            allowSourceCard: false,
          },
        },
      ],
    },
    {
      id: "support-wind-001",
      name: "追い風",
      attribute: "attributeC",
      cardType: "support",
      cost: 1,
      duration: "instant",
      effects: [
        {
          effectId: "restore-stamina",
          type: "changeStamina",
          activationType: "onPlay",
          amount: 2,
          targetRule: {
            required: true,
            minTargets: 1,
            maxTargets: 1,
            side: "self",
            zones: ["player"],
            allowSourceCard: false,
          },
        },
      ],
    },
    {
      id: "support-wind-003",
      name: "陣形崩壊",
      attribute: "attributeC",
      cardType: "support",
      cost: 4,
      duration: "instant",
      effects: [
        {
          effectId: "remove-opponent-group",
          type: "removeAttackGroup",
          activationType: "onPlay",
          targetRule: {
            required: true,
            minTargets: 1,
            maxTargets: 1,
            side: "opponent",
            zones: ["attackGroup"],
            allowSourceCard: false,
          },
        },
      ],
    },
    {
      id: "support-fire-004",
      name: "破壊と補給",
      attribute: "attributeA",
      cardType: "support",
      cost: 5,
      duration: "instant",
      effects: [
        {
          effectId: "remove-group",
          type: "removeAttackGroup",
          activationType: "onPlay",
          targetRule: {
            required: true,
            minTargets: 1,
            maxTargets: 1,
            side: "opponent",
            zones: ["attackGroup"],
            allowSourceCard: false,
          },
        },
        {
          effectId: "draw-one",
          type: "drawCards",
          activationType: "onPlay",
          count: 1,
          targetRule: {
            required: false,
            minTargets: 0,
            maxTargets: 0,
            side: "self",
            zones: [],
            allowSourceCard: false,
          },
        },
      ],
    },
  ],
};

const initialStarterDeckDefinitionIds = [
  "mana-a",
  "mana-a",
  "mana-a",
  "mana-b",
  "mana-b",
  "mana-b",
  "mana-c",
  "mana-c",
  "attack-1",
  "attack-1",
  "attack-2",
  "attack-2",
  "attack-3",
  "attack-3",
  "attack-4",
  "attack-4",
  "attack-5",
  "attack-5",
  "attack-6",
  "attack-6",
  "attack-7",
  "attack-7",
  "attack-8",
  "attack-8",
  "support-fire-001",
  "support-water-001",
  "support-water-002",
  "support-wind-001",
  "support-wind-003",
  "support-fire-004",
];

export function createInitialStarterDeckDefinitionIds(): string[] {
  return [...initialStarterDeckDefinitionIds];
}
